/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Wordle;

public class App {

    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_GREEN_BACKGROUND = "\u001B[32m";
    public static final String ANSI_YELLOW_BACKGROUND = "\u001B[33m";
    public static final String ANSI_RED_BACKGROUND = "\u001B[31m";
    public static void displayRules() {
        System.out.println("You have to guess a 5-letter word.");
        System.out.println("You have 6 chances. In every chance, we will confirm which letters the chosen word and the word you have guessed have in common:");
        System.out.println("Letters highlighted in " + ANSI_GREEN_BACKGROUND + "green" + ANSI_RESET + " are in the right place.");
        System.out.println("Letters highlighted in " + ANSI_YELLOW_BACKGROUND + "yellow" + ANSI_RESET + " appear in the chosen word but in a different place.");
        System.out.println("Letters highlighted in " + ANSI_RED_BACKGROUND + "red" + ANSI_RESET + " do not appear in the chosen word.");
    }

    public static void askForGuess() {
        System.out.println("Please make your first guess:");
    }
    public static void main(String[] args) {
    System.out.println("Welcome to Wordle");
    displayRules();
    askForGuess();
    Game startGame = new Game();
    startGame.start();
    }
}
